apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-deployment
  # labels:
  #   type: service
  #   name: listings
spec:
  replicas: 3
  selector:
    matchLabels:
      type: service
      name: listings
  template:
    metadata:
      labels:
        type: service
        name: listings
    spec:
      containers:
      - name: listings
        image: listings-service
        # imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: listings
spec:
  type: LoadBalancer
  selector:
    type: service
    name: listings
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080