apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: flower-fixed
        ports:
          - containerPort: 5555
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: main-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: main-config
              key: CELERY_RESULT_BACKEND
---
apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  type: LoadBalancer
  selector:
    app: flower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555