kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data/rabbitmq"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeName: "rabbitmq-volume"
---
kind: Pod
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
  - image: rabbitmq:3.7-management
    name: rabbitmq
#        env:
#        - name: RABBITMQ_DEFAULT_USER
#          value: user
#        - name: RABBITMQ_DEFAULT_PASS
#          value: password
    ports:
    - containerPort: 5672
    - containerPort: 15672
    volumeMounts:
    - mountPath: "/var/lib/rabbitmq"
      name: rabbitmq-storage
  volumes:
  - name: rabbitmq-storage
    persistentVolumeClaim:
      claimName: rabbitmq-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: "5672"
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui
spec:
  type: LoadBalancer
  ports:
  - name: "15672"
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
