apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listings
  template:
    metadata:
      labels:
        app: listings
    spec:
      containers:
      - name: listings
        image: listings-service
        # imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: main-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: main-config
              key: CELERY_RESULT_BACKEND
        volumeMounts:
        - name: gcp-service-account-volume
          mountPath: "/etc/app/secrets"
          readOnly: true
      volumes:
      - name: gcp-service-account-volume
        secret:
          secretName: gcp-service-account
          items:
          - key: gcp-service-account.json
            path: gcp-service-account.json
---
apiVersion: v1
kind: Service
metadata:
  name: listings
spec:
  type: LoadBalancer
  selector:
    app: listings
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080