apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings-deployment
  labels:
    my-type: service
    my-service: listings
spec:
  replicas: 3
  selector:
    matchLabels:
      my-type: service
      my-service: listings
  template:
    metadata:
      labels:
        my-type: service
        my-service: listings
    spec:
      containers:
      - name: listings
        image: my-listings-service-image
        # imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: listings
spec:
  type: LoadBalancer
  selector:
    my-type: service
    my-service: listings
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 8080